version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/web
    container_name: belhard-web
    ports:
      - "8001:8000"
    restart: always
    environment:
      - SECRET_KEY=161d39e61c93ce944a0573e45b4360eec9f28431c2a57d7f8d76c4783ebc3626
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1 0.0.0.0
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=belhard
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: belhard-database
    hostname: postgres
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=belhard
      - POSTGRES_HOST_AUTH_METHOD=trust